apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web-pod
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          image: ispassov/k8s-springboot-mysql:2.3
          ports:
            - containerPort: 8080
